source "https://rubygems.org"
gem "github-pages"
# gem "jekyll"
gem "jekyll-sitemap"
gem "jekyll-redirect-from"
gem "jekyll-remote-theme"
gem "jekyll-youtube"
gem "kramdown-parser-gfm"
gem "minima"
gem "webrick"
